# read_capacity / write_capacity come from capacity.auto.tfvars, generated by /slo.

task_cpu      = 256
task_memory   = 512
desired_count = 1

# Calibrated on a real 0.25 vCPU Fargate slice for ~1.4ms per report request (Task 17).
# Two one-off Fargate runs: 2653 and 2698 iterations (1.7% apart); value is their mean.
# Re-calibrate if task_cpu changes — this number is CPU-specific.
pbkdf2_iterations = 2675
feed_page_size    = 20

autoscaling_enabled = false
