# No read_capacity / write_capacity here. capacity.auto.tfvars (generated by /slo from
# the 1000 rps capacity model) supplies 1,025 RCU / 200 WCU on its own -- do not edit
# that file, it is generated and byte-checked by `npm run slo:check`. Do NOT re-add
# read_capacity / write_capacity lines to this file: a CLI -var-file outranks an
# auto-loaded *.auto.tfvars, so two lines here would silently override the model
# again, which is exactly what happened until 2026-09-15 (1,000/500 here beat the
# model's 1,025/200, 25 RCU short and invisible until the service could push real rps).
#
# WCU sanity check: run 8554820 measured 33.5 WCU/s at ~175 rps, i.e. 0.19 WCU/rps, so
# 1,000 rps predicts ~191 WCU -- the model's 200 is sized against that measurement, not
# guessed.
task_cpu    = 256
task_memory = 512

# Terraform owns this floor too -- see the comment above `desired_count =
# var.desired_count` in ecs.tf: Application Auto Scaling's min_capacity (autoscaling.tf)
# now derives from this same variable instead of a second, separate floor variable, so
# the floor and the baseline cannot drift apart the way they did in run 8554820.
desired_count = 1

# Calibrated on a real 0.25 vCPU Fargate slice for ~1.4ms of pbkdf2 per report
# request. Re-measured 2026-08-31 on the instrumented build: two one-off Fargate
# runs returned 2665 and 2659 (0.23% apart); value is their mean.
#
# READ THIS BEFORE CONCLUDING THE INSTRUMENTATION MOVED IT. It did not, and this
# calibration cannot see it either way: scripts/calibrate.js imports burn() from
# cpu.js and binary-searches it in isolation -- no HTTP, no server.js, no otel.js.
# The -0.49% against the previous 2675 is host-to-host variance, only twice the
# 0.23% spread between two runs on the same day.
#
# The instrumentation cost is real but far below this measurement's noise floor:
# 0.51 us/request (scripts/bench-otel.js, 200k iterations) is 0.036% of the 1.4ms
# target, i.e. about ONE iteration. Measuring it here would need a calibration
# that drives the whole request path, not burn() alone.
#
# Re-calibrate if task_cpu changes — this number is CPU-specific.
pbkdf2_iterations = 2662
feed_page_size    = 20

autoscaling_enabled = true

# Off for the baseline stress run (spike-response plan Task 4), which must
# measure the CPU-only policy alone. The Change 1 re-measure (Task 6) flips
# this to true and changes nothing else, so the before/after comparison
# changes exactly one knob from the same commit.
requests_scaling_enabled = false
