# Capacity is PINNED to the DynamoDB free tier for the SLI-collection work.
#
# capacity.auto.tfvars (generated by /slo from the 1000 rps capacity model) asks for
# 1025/200, ~$0.32/hour. That raise belongs to the 2026-08-29 plan's Task 18, alongside
# the load runs that need it -- not to the collector work, which measures nothing that
# depends on table capacity. Terraform ranks a CLI -var-file above an auto-loaded
# *.auto.tfvars, so these two lines win while every plan/apply passes -var-file=dev.tfvars.
#
# To raise capacity (old plan, Task 18): DELETE these two lines. capacity.auto.tfvars
# then applies on its own -- do not edit that file, it is generated and byte-checked by
# `npm run slo:check`.
read_capacity  = 25
write_capacity = 25

task_cpu      = 256
task_memory   = 512
desired_count = 1

# Calibrated on a real 0.25 vCPU Fargate slice for ~1.4ms of pbkdf2 per report
# request. Re-measured 2026-08-31 on the instrumented build: two one-off Fargate
# runs returned 2665 and 2659 (0.23% apart); value is their mean.
#
# READ THIS BEFORE CONCLUDING THE INSTRUMENTATION MOVED IT. It did not, and this
# calibration cannot see it either way: scripts/calibrate.js imports burn() from
# cpu.js and binary-searches it in isolation -- no HTTP, no server.js, no otel.js.
# The -0.49% against the previous 2675 is host-to-host variance, only twice the
# 0.23% spread between two runs on the same day.
#
# The instrumentation cost is real but far below this measurement's noise floor:
# 0.51 us/request (scripts/bench-otel.js, 200k iterations) is 0.036% of the 1.4ms
# target, i.e. about ONE iteration. Measuring it here would need a calibration
# that drives the whole request path, not burn() alone.
#
# Re-calibrate if task_cpu changes — this number is CPU-specific.
pbkdf2_iterations = 2662
feed_page_size    = 20

autoscaling_enabled = false
